# This workflow will test that the Project builds successfully
name: Project Build Test

on:
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Setup node
          uses: actions/setup-node@v3
  
        - name: Clean Install
          run: npm ci
  
        - name: Build Repo
          run: npm run build
